# Generated by Django 2.2.12 on 2021-02-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BieleGastosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(max_length=2)),
                ('dia', models.IntegerField(max_length=2)),
                ('mes', models.IntegerField(max_length=2)),
                ('dia_sem', models.IntegerField(max_length=1)),
                ('codigo', models.IntegerField(max_length=1)),
            ],
        ),
    ]
