# Generated by Django 2.2.12 on 2021-02-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BieleGastosApp', '0003_auto_20210205_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'ordering': ('semana', 'mes', 'dia'), 'verbose_name': 'calendario'},
        ),
    ]
