# Generated by Django 2.2.12 on 2021-02-08 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BieleGastosApp', '0004_auto_20210205_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('slug', models.SlugField()),
                ('concepto', models.CharField(max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=25)),
                ('notas', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ('autor', 'dia'),
            },
        ),
    ]
